[build]
  publish = "build/"
  command = "yarn build"

[build.environment]
  CI = "true"
  GENERATE_SOURCEMAP = "true"
  YARN_VERSION = "1.21.0"
  NODE_VERSION = "12.14.1"


# Redirect everything to index.html for client-side
# routing in Single Page Applications.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
